/**
 * Do not alter! This code is generated by the sailfishc
 * compiler and might/will break if anything changed.
 */
#include "stdlib/stdlib.h"

typedef struct _Counter_ {
    int count;
    char* finish_msg;
} Counter;

Counter*
construct_Counter(int count_,char* finish_msg_)
{
    Counter* a____struct___generated = (Counter*)malloc(sizeof(Counter));
    a____struct___generated->count = count_;    a____struct___generated->finish_msg = finish_msg_;
    return a____struct___generated;
}

void
decrement(Counter* _own_)
{
    _own_->count = _own_->count-1;
    print_int(_own_->count);
    print_str("\n");
}
void
increment(Counter* _own_)
{
    _own_->count = _own_->count+1;
    print_int(_own_->count);
    print_str("\n");
}
void
countdown(Counter* _own_)
{
    if(_own_->count>0)
{
    decrement(_own_);
    countdown(_own_);
}
else 
{
    print_str(_own_->finish_msg);
}

}
int
main()
{
    Counter* _c_ = construct_Counter(10,"Blast off!\n");
    countdown(_c_);
}
