/**
 * Do not alter! This code is generated by the sailfishc
 * compiler and might/will break if anything changed.
 */
#include "stdlib/display.h"

typedef struct _Stack_ {
    int size;
} Stack;

Stack*
construct_Stack(int size_)
{
    Stack* a = (Stack*)malloc(sizeof(Stack));
    a->size = size_;
    return a;
}

int
is_empty(Stack* _own_)
{
    int ret_val = 1;
    ret_val = (0==1);
    return ret_val;
}
int
main()
{
    Stack* s = construct_Stack(10);
    int c = is_empty(s);
}
